/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#ba85fb",
        "error-container": "#b92902",
        "surface-container-lowest": "#000000",
        "surface-variant": "#262626",
        "inverse-surface": "#fcf9f8",
        "on-primary": "#614700",
        "on-secondary-fixed": "#4a0b87",
        "on-tertiary": "#00645a",
        "primary": "#ffd16f",
        "inverse-primary": "#7a5a00",
        "background": "#0e0e0e",
        "error-dim": "#d53d18",
        "outline-variant": "#484847",
        "tertiary": "#a0fff0",
        "on-tertiary-fixed-variant": "#00655b",
        "surface-dim": "#0e0e0e",
        "surface-container-high": "#20201f",
        "primary-dim": "#eeb200",
        "on-secondary-container": "#e1c5ff",
        "on-secondary-fixed-variant": "#6834a6",
        "on-primary-container": "#563e00",
        "on-error-container": "#ffd2c8",
        "on-surface": "#ffffff",
        "surface-tint": "#ffd16f",
        "surface-bright": "#2c2c2c",
        "primary-container": "#ffbf00",
        "surface-container": "#1a1a1a",
        "tertiary-container": "#4af8e3",
        "secondary": "#bc87fe",
        "primary-fixed": "#ffbf00",
        "tertiary-dim": "#2de7d2",
        "on-error": "#450900",
        "secondary-container": "#5e289b",
        "error": "#ff7351",
        "on-background": "#ffffff",
        "tertiary-fixed": "#4af8e3",
        "on-secondary": "#340064",
        "surface-container-highest": "#262626",
        "on-tertiary-fixed": "#00463f",
        "on-primary-fixed-variant": "#614700",
        "inverse-on-surface": "#565555",
        "on-primary-fixed": "#3d2b00",
        "secondary-fixed": "#e2c7ff",
        "outline": "#767575",
        "on-tertiary-container": "#005b51",
        "surface-container-low": "#131313",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed-dim": "#33e9d5",
        "primary-fixed-dim": "#eeb200",
        "secondary-fixed-dim": "#d7b5ff",
        "surface": "#0e0e0e"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "Noto Sans SC"],
        "body": ["Be Vietnam Pro", "Noto Sans SC"],
        "label": ["Be Vietnam Pro", "Noto Sans SC"]
      }
    },
  },
  plugins: [],
}
